trigger:
  branches:
    include:
    - main
  paths:
    include:
    - infra/terraform/*

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: terraform-variables

stages:
- stage: 'Validate'
  displayName: 'Validate'
  jobs:
  - job: 'Validate'
    displayName: 'Validate Terraform'
    steps:
    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'

    - task: TerraformCLI@1
      displayName: 'Terraform Init'
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform'
      env:
        TF_TOKEN_app_terraform_io: $(TF_API_TOKEN)

    - task: TerraformCLI@1
      displayName: 'Terraform Format'
      inputs:
        command: 'fmt'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform'

    - task: TerraformCLI@1
      displayName: 'Terraform Validate'
      inputs:
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform'

- stage: 'Plan'
  displayName: 'Plan'
  dependsOn: 'Validate'
  jobs:
  - job: 'Plan'
    displayName: 'Terraform Plan'
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformCLI@1
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform'
        backendType: 'remote'
        backendServiceArm: 'terraform-cloud-service-connection'

    - task: TerraformCLI@1
      inputs:
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform'
        environmentServiceNameAzureRM: 'Azure-Service-Connection'

- stage: 'Apply'
  displayName: 'Apply'
  dependsOn: 'Plan'
  condition: succeeded()
  jobs:
  - deployment: 'Apply'
    displayName: 'Terraform Apply'
    environment: 'development'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - task: TerraformCLI@1
            inputs:
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform'
            env:
              TF_TOKEN_app_terraform_io: $(TF_API_TOKEN)
              ARM_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(AZURE_TENANT_ID)
              ARM_CLIENT_ID: $(AZURE_CLIENT_ID)
              ARM_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)

          - task: TerraformCLI@1
            inputs:
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform'
              commandOptions: '-auto-approve'
            env:
              TF_TOKEN_app_terraform_io: $(TF_API_TOKEN)
              ARM_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(AZURE_TENANT_ID)
              ARM_CLIENT_ID: $(AZURE_CLIENT_ID)
              ARM_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)