trigger:
  branches:
    include:
    - main
  paths:
    include:
    - infra/terraform/*

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: terraform-variables

stages:
- stage: 'Validate'
  displayName: 'Validate'
  jobs:
  - job: 'Validate'
    displayName: 'Validate Terraform'
    steps:
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform'
        backendServiceArm: 'Azure-Service-Connection'
        backendType: 'azurerm'
      env:
        TF_TOKEN_app_terraform_io: $(TF_API_TOKEN)
        ARM_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(AZURE_TENANT_ID)
        ARM_CLIENT_ID: $(AZURE_CLIENT_ID)
        ARM_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
      displayName: 'Terraform Format'
      inputs:
        provider: 'azurerm'
        command: 'fmt'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform'

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
      displayName: 'Terraform Validate'
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform'

- stage: 'Plan'
  displayName: 'Plan'
  dependsOn: 'Validate'
  jobs:
  - job: 'Plan'
    displayName: 'Terraform Plan'
    steps:
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform'
        backendServiceArm: 'Azure-Service-Connection'
        backendType: 'azurerm'
      env:
        TF_TOKEN_app_terraform_io: $(TF_API_TOKEN)
        ARM_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(AZURE_TENANT_ID)
        ARM_CLIENT_ID: $(AZURE_CLIENT_ID)
        ARM_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform'
        environmentServiceNameAzureRM: 'Azure-Service-Connection'
      env:
        TF_TOKEN_app_terraform_io: $(TF_API_TOKEN)
        ARM_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(AZURE_TENANT_ID)
        ARM_CLIENT_ID: $(AZURE_CLIENT_ID)
        ARM_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)

- stage: 'Apply'
  displayName: 'Apply'
  dependsOn: 'Plan'
  condition: succeeded()
  jobs:
  - deployment: 'Apply'
    displayName: 'Terraform Apply'
    environment: 'development'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: 'latest'

          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
            displayName: 'Terraform Init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform'
              backendServiceArm: 'Azure-Service-Connection'
              backendType: 'azurerm'
            env:
              TF_TOKEN_app_terraform_io: $(TF_API_TOKEN)
              ARM_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(AZURE_TENANT_ID)
              ARM_CLIENT_ID: $(AZURE_CLIENT_ID)
              ARM_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)

          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
            displayName: 'Terraform Apply'
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform'
              environmentServiceNameAzureRM: 'Azure-Service-Connection'
            env:
              TF_TOKEN_app_terraform_io: $(TF_API_TOKEN)
              ARM_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(AZURE_TENANT_ID)
              ARM_CLIENT_ID: $(AZURE_CLIENT_ID)
              ARM_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)

- stage: 'Destroy'
  displayName: 'Destroy Infrastructure'
  condition: eq(variables['TERRAFORM_DESTROY'], 'true')
  dependsOn: []
  jobs:
  - deployment: 'Destroy'
    displayName: 'Terraform Destroy'
    environment: 'development'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: 'latest'

          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
            displayName: 'Terraform Init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform'
              backendServiceArm: 'Azure-Service-Connection'
              backendType: 'azurerm'
            env:
              TF_TOKEN_app_terraform_io: $(TF_API_TOKEN)
              ARM_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(AZURE_TENANT_ID)
              ARM_CLIENT_ID: $(AZURE_CLIENT_ID)
              ARM_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)

          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
            displayName: 'Terraform Destroy'
            inputs:
              provider: 'azurerm'
              command: 'destroy'
              workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform'
              environmentServiceNameAzureRM: 'Azure-Service-Connection'
            env:
              TF_TOKEN_app_terraform_io: $(TF_API_TOKEN)
              ARM_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(AZURE_TENANT_ID)
              ARM_CLIENT_ID: $(AZURE_CLIENT_ID)
              ARM_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)