trigger:
  branches:
    include:
    - main
  paths:
    include:
    - infra/terraform/*

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: terraform-variables  # Create this variable group in Azure DevOps

stages:
- stage: 'Terraform'
  displayName: 'Terraform Infrastructure Deployment'
  jobs:
  - job: 'Terraform'
    displayName: 'Terraform'
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform'
        backendServiceArm: 'Azure-Service-Connection'  # Create this service connection in Azure DevOps
        backendAzureRmResourceGroupName: '$(RESOURCE_GROUP_NAME)'
        backendAzureRmStorageAccountName: '$(STORAGE_ACCOUNT_NAME)'
        backendAzureRmContainerName: '$(CONTAINER_NAME)'
        backendAzureRmKey: 'terraform.tfstate'
    
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform'
        environmentServiceNameAzureRM: 'Azure-Service-Connection'
    
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform'
        environmentServiceNameAzureRM: 'Azure-Service-Connection'